# Generated by Django 4.2.3 on 2023-07-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "idpais",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("codigo", models.CharField(max_length=10)),
                ("nombre", models.CharField(max_length=10)),
                ("poblacion", models.CharField(max_length=10)),
                ("estado", models.CharField(max_length=10)),
            ],
        ),
    ]
